description: First Certificate
title: TEC
cta:
  version: null
  bucket: null
  domain: null
layout_spectrum: 0.2748735
favicon: null
name: the english company
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.3125
  saturation: 0.5773104748222977
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  lightness: 0.1461248470004648
  rhythmicContrast: 0.777684535831213
typography_spectrum: 0.4595745
